### ISSUE TITLE
Merging from devel to master

### ISSUE THREAD

**Issue by IzzySoft** [Benjol/SE-AutoReviewComments#119]
@Benjol would you consider merging (and declaring 1.4.1 a release)? There are bug fixes in devel sitting there for over a year now. Took me almost an hour to figure why userinfo wasn't retrieved on a new installation – a bug I've fixed with 80b4075 in March 2015 (the corresponding issue #87 was closed the same month).

In case you're busy elsewhere, maybe @oliversalzburg could do this? ;)

Thanks in advance!

**Comment by Benjol** [comment]
Yeah, sorry.
I haven't been very active at all, and right now I can't even get git pull
working properly here (cert issues, drives me up the wall).

Also, I must admit I never really got my head around the way Caleb set up
the build/release cycle.

Another problem is I believe I'm the only person who can release the Chrome
and Firefox addins (or upload them). Though I guess I can probably still do
that if someone else does the donkey work.

Paging @oliversalzburg....

Failing that I could just give you owner access on here too

**Comment by oliversalzburg** [comment]
We won't be able to release the Firefox extension, because Mozilla changed their extension infrastructure *again* and they're no longer accepting extension updates built with the previous version of their SDK. The migration documentation was a joke, the last time I checked.

I'd be happy to merge up a new release.

**Comment by oliversalzburg** [comment]
There already is a [1.4.1 release](https://github.com/Benjol/SE-AutoReviewComments/releases/tag/v1.4.1), but, I guess, it was never published? I'll try to push a 1.4.2 now.

**Comment by Benjol** [comment]
One of you guys should get hired by SE, then you could integrate it there
and save us all the trouble :)

**Comment by oliversalzburg** [comment]
@Benjol I rather stay with my own company ;)

Also, [1.4.2](https://github.com/Benjol/SE-AutoReviewComments/releases/tag/v1.4.2) is released. I guess you can use the binaries to publish to Chrome Webstore. If there's anything else I can do, let me know and I'll try to squeeze it in.

**Comment by IzzySoft** [comment]
I'd even go so far as to drop the FF addon altogether. I never used it, and Greasemonkey plus the UserScript are just working fine. So why taking the trouble (except, maybe, for being afraid Greasemonkey might disappear)?

Alternatively, the UserScript could be separated (and used as "module" in this git repo), so updates to it wouldn't depend on Firefox troubles being solved.

Thanks again @oliversalzburg for making the release!

**Comment by Benjol** [comment]
@oliversalzburg, @IzzySoft 
Updated in Webstore. Following your comments, I won't bother with FFx for the moment :)

**Comment by Benjol** [comment]
@oliversalzburg, @IzzySoft 

More hassle from Mozilla:

Your add-on, SE-AutoReviewComments, has been automatically signed.

We recently discovered a problem with the expiration date of add-on signatures.
As a result, for the next few weeks Firefox will not be able to recognize the signatures of some add-ons. We are contacting you because your add-on, SE-AutoReviewComments, is affected.

To address this problem, we're signing the affected add-ons again and letting you know in case you need to deploy this update to your users. The details of this issue can be found here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1267318

This signing process involved re-packaging add-on files and adding the string '.1-signed' to their version numbers. The current review status of your add-on will remain the same. Alternatively, you can upload a new version and have it signed through the usual means.

If you have any questions or need support, please reply to this email or join #addons on irc.mozilla.org and we'll do our best to help.

You are receiving this email because you have an add-on on https://addons.mozilla.org

**Comment by IzzySoft** [comment]
That "enforced signing stuff" is nothing but trouble (and one of the reasons I'm still on FF43 – as starting with FF44 one no longer can use unsigned addons). I never understood why one wanted to convert UserScripts to Addons anyhow: even for unexperienced users, it's easy to just install Greasemonkey and use the scripts.

Well, I was never involved in the addon part, so it's not me to decide. But the question is whether the addon is worth the trouble, when one can use the UserScript easily instead.

**Comment by oliversalzburg** [comment]
The Firefox addon is probably a lost cause. I got the same email regarding other addons of mine and I won't do anything about those either. I simply don't have the time :(

**Comment by IzzySoft** [comment]
I only hope enough devs deal with it that time, so Moz rethinks the issue and brings back the possibility to use unsigned addons again. Maybe you ( @oliversalzburg ) should add the very same comment you've just made here to the issue linked by Moz? After all, with their "security feature" they're eating the time, efforts and fruits of the addon devs.

**Comment by oliversalzburg** [comment]
@IzzySoft For me the issue starts much earlier. Even if I wanted to sign my addon, I couldn't because I would need to build it with a new toolset and the migration path is unclear. So, meh.

**Comment by IzzySoft** [comment]
So without the signing requirement, it could be available to users – but thanks to the fact that users no longer can install unsigned addons, it's not. Thanks, Moz, for forcing upon us that kind of security: "what you can't install cannot affect your security", sure :rage: I wish there were a "compatible, slim alternative" working with all the addons but without the added crap.
